[tool.poetry]
name = "classbot"
version = "0.1.0"
description = "classbot"
authors = ["2711402357@qq.com"]
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = ">=3.12,<3.13"
nonebot2 = {extras = ["httpx", "fastapi", "aiohttp"], version = "^2.5.0"}
pandas = {extras = ["tabulate"], version = "^2.3.3"}
nonebot-adapter-onebot = "^2.4.6"
nonebot-adapter-qq = "^1.6.7"
nonebot-plugin-orm = {extras = ["postgresql", "asyncpg", "aiosqlite"], version = "^0.8.1"}
nonebot-plugin-alconna = "^0.62.0"
nonebot-plugin-animeres = "^1.0.5"
nonebot-plugin-localstore = "^0.7.4"
nonebot-plugin-apscheduler = "^0.5.0"
nonebot-plugin-htmlrender = "^0.6.6"
nonebot-plugin-status = "^0.9.0"
nonebot-plugin-waiter = "^0.8.1"
nonebot-plugin-userinfo = "^0.2.6"
bs4 = "^0.0.2"
qrcode = "^8.2"
strenum = "^0.4.15"
cos-python-sdk-v5 = "^1.9.37"
pydantic = "^1.0.0"
filetype = "^1.2.0"
pillow = "^12.2.0"
opencv-python = "^4.13.0.92"
openai = "^2.32.0"
playwright = "^1.53.0"
pyzbar = "^0.1.9"
markdown2 = "^2.5.3"
pypandoc = "^1.15"
pdf2image = "^1.17.0"
comtypes = "^1.4.11"
onnxruntime = "^1.22.0"
async-timeout = "^5.0.1"
hiredis = "^3.2.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.2.0"
autoflake = "^2.3.1"
isort = "^8.0.1"
black = "^26.3.1"

[tool.poetry.group.test.dependencies]
pytest = "^9.0.2"
pytest-asyncio = "^1.3.0"
nonebug = "^0.4.3"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"
testpaths = ["tests"]

[[tool.poetry.source]]
name = "tencent"
url = "https://mirrors.cloud.tencent.com/pypi/simple"
priority = "primary"

[[tool.poetry.source]]
name = "pypi-official"
url = "https://pypi.python.org/simple"
priority = "supplemental"

[tool.nonebot]
plugins = [
    "nonebot_plugin_alconna",
    "nonebot_plugin_orm",
    "nonebot_plugin_htmlrender",
    "nonebot_plugin_animeres",
    "nonebot_plugin_localstore",
    "nonebot_plugin_apscheduler",
    "nonebot_plugin_status",
    "nonebot_plugin_waiter",
    "utils.models",
]
plugin_dirs = [
    "src/managers",
    "src/plugins",
    "src/others",
    "src/routers",
    "src/extensions",
]
adapters = [
    {name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11"},
    {name = "OneBot V12", module_name = "nonebot.adapters.onebot.v12"},
    {name = "QQ", module_name = "nonebot.adapters.qq"},
]
[tool.black]
line-length = 120
target-version = ["py38", "py39", "py310", "py311"]
include = '\.pyi?$'
extend-exclude = '''
'''

[tool.isort]
profile = "black"
line_length = 120
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
src_paths = ["nonebot", "tests"]
extra_standard_library = ["typing_extensions"]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
