"""empty message

迁移 ID: 10ae65bbe3dd
父迁移: a172aeed2c22
创建时间: 2025-02-18 18:53:53.384863

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "10ae65bbe3dd"
down_revision: str | Sequence[str] | None = "a172aeed2c22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models_classesleaveconfig",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column(
            "notify_role", sa.String(length=255), server_default="[]", nullable=False
        ),
        sa.Column(
            "create_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "update_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["classes.id"],
            name=op.f("fk_models_classesleaveconfig_classes_id_classes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models_classesleaveconfig")),
        sa.UniqueConstraint("classes_id"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "models_studentleave",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["classes.id"],
            name=op.f("fk_models_studentleave_classes_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["models_files.id"],
            name=op.f("fk_models_studentleave_file_id_models_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name=op.f("fk_models_studentleave_student_id_student"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models_studentleave")),
        info={"bind_key": "models"},
    )
    op.drop_table("models_leave")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models_leave",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "start_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "end_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "reason", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("file_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("classes_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("student_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["classes.id"],
            name="fk_models_leave_classes_id_classes",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["models_files.id"],
            name="fk_models_leave_file_id_models_files",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name="fk_models_leave_student_id_student",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_models_leave"),
    )
    op.drop_table("models_studentleave")
    op.drop_table("models_classesleaveconfig")
    # ### end Alembic commands ###
