"""empty message

迁移 ID: 2072b25f0341
父迁移: 01b87213d310
创建时间: 2025-01-17 01:05:53.223377

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2072b25f0341"
down_revision: str | Sequence[str] | None = "01b87213d310"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models_classesjoinrequest",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("join_method", sa.String(length=32), nullable=False),
        sa.Column("describe", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["classes.id"],
            name=op.f("fk_models_classesjoinrequest_classes_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_models_classesjoinrequest_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models_classesjoinrequest")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "join_method",
                sa.String(length=32),
                server_default="direct",
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("classes", schema=None) as batch_op:
        batch_op.drop_column("join_method")

    op.drop_table("models_classesjoinrequest")
    # ### end Alembic commands ###
