"""empty message

迁移 ID: 21858dcc2085
父迁移: e634135c3647
创建时间: 2025-04-25 00:07:46.959463

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "21858dcc2085"
down_revision: str | Sequence[str] | None = "e634135c3647"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_leave_config",
        sa.Column("classes_id", sa.Integer(), nullable=True),
        sa.Column("school_id", sa.Integer(), nullable=True),
        sa.Column("workflow", sa.JSON(), server_default="[]", nullable=False),
        sa.Column(
            "create_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "update_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["bot_classes.id"],
            name=op.f("fk_bot_leave_config_classes_id_bot_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["bot_school.id"],
            name=op.f("fk_bot_leave_config_school_id_bot_school"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_leave_config")),
        sa.UniqueConstraint("classes_id"),
        sa.UniqueConstraint("school_id"),
        info={"bind_key": "models"},
    )
    op.drop_table("bot_classes_leave_config")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_classes_leave_config",
        sa.Column("classes_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "notify_role",
            sa.VARCHAR(length=255),
            server_default=sa.text("'[]'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "create_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "update_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["bot_classes.id"],
            name="fk_bot_classes_leave_config_classes_id_bot_classes",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_bot_classes_leave_config"),
        sa.UniqueConstraint(
            "classes_id", name="bot_classes_leave_config_classes_id_key"
        ),
    )
    op.drop_table("bot_leave_config")
    # ### end Alembic commands ###
