"""empty message

迁移 ID: 329a5004bb75
父迁移: 818b0076e3bf
创建时间: 2025-03-23 13:37:45.268135

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "329a5004bb75"
down_revision: str | Sequence[str] | None = "818b0076e3bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bind", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("platform_name", sa.String(length=255), nullable=True)
        )

    with op.batch_alter_table("group_bind", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("platform_name", sa.String(length=255), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_bind", schema=None) as batch_op:
        batch_op.drop_column("platform_name")

    with op.batch_alter_table("bind", schema=None) as batch_op:
        batch_op.drop_column("platform_name")

    # ### end Alembic commands ###
