"""empty message

迁移 ID: 3a0e30e24cb5
父迁移: 
创建时间: 2025-01-06 16:37:16.824230

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3a0e30e24cb5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nickname", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bind",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform_id", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_bind_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bind")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("bind", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bind_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_bind_platform_id"), ["platform_id"], unique=False
        )

    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["user.id"], name=op.f("fk_group_creator_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "models_teacher",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_models_teacher_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models_teacher")),
        sa.UniqueConstraint("user_id"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "group_bind",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform_id", sa.String(length=32), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=True),
        sa.Column("guild_id", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
            name=op.f("fk_group_bind_group_id_group"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_bind")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("group_bind", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_group_bind_channel_id"), ["channel_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_group_bind_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_group_bind_platform_id"), ["platform_id"], unique=False
        )

    op.create_table(
        "models_classes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
            name=op.f("fk_models_classes_group_id_group"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models_classes")),
        sa.UniqueConstraint("group_id"),
        info={"bind_key": "models"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("models_classes")
    with op.batch_alter_table("group_bind", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_group_bind_platform_id"))
        batch_op.drop_index(batch_op.f("ix_group_bind_guild_id"))
        batch_op.drop_index(batch_op.f("ix_group_bind_channel_id"))

    op.drop_table("group_bind")
    op.drop_table("models_teacher")
    op.drop_table("group")
    with op.batch_alter_table("bind", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bind_platform_id"))
        batch_op.drop_index(batch_op.f("ix_bind_account_id"))

    op.drop_table("bind")
    op.drop_table("user")
    # ### end Alembic commands ###
