"""empty message

迁移 ID: 48610db94b76
父迁移: 0b14a3e3db26
创建时间: 2025-04-02 11:43:14.360528

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "48610db94b76"
down_revision: str | Sequence[str] | None = "0b14a3e3db26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot_group", schema=None) as batch_op:
        batch_op.add_column(sa.Column("school_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("college_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_bot_group_school_id_bot_school"),
            "bot_school",
            ["school_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_bot_group_college_id_bot_college"),
            "bot_college",
            ["college_id"],
            ["id"],
        )

    with op.batch_alter_table("bot_teacher", schema=None) as batch_op:
        batch_op.add_column(sa.Column("school_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("college_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_bot_teacher_school_id_bot_school"),
            "bot_school",
            ["school_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_bot_teacher_college_id_bot_college"),
            "bot_college",
            ["college_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot_teacher", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_bot_teacher_college_id_bot_college"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_bot_teacher_school_id_bot_school"), type_="foreignkey"
        )
        batch_op.drop_column("college_id")
        batch_op.drop_column("school_id")

    with op.batch_alter_table("bot_group", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_bot_group_college_id_bot_college"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_bot_group_school_id_bot_school"), type_="foreignkey"
        )
        batch_op.drop_column("college_id")
        batch_op.drop_column("school_id")

    # ### end Alembic commands ###
