"""empty message

迁移 ID: 488b5ff5a73e
父迁移: 6206e8c32ed6
创建时间: 2025-02-05 13:04:24.327172

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "488b5ff5a73e"
down_revision: str | Sequence[str] | None = "6206e8c32ed6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_md5", sa.String(length=32), nullable=False))
        batch_op.create_unique_constraint(None, ["file_md5"])

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_files", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("file_md5")

    # ### end Alembic commands ###
