"""empty message

迁移 ID: 4931351cb309
父迁移: 8419a3b15155
创建时间: 2025-05-11 00:30:52.849307

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4931351cb309"
down_revision: str | Sequence[str] | None = "8419a3b15155"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot_student", schema=None) as batch_op:
        batch_op.drop_constraint("bot_student_extra_id_key", type_="unique")
        batch_op.drop_constraint(
            "fk_bot_student_extra_id_bot_student_extra", type_="foreignkey"
        )
        batch_op.drop_column("extra_id")

    with op.batch_alter_table("bot_student_extra", schema=None) as batch_op:
        batch_op.add_column(sa.Column("student_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_bot_student_extra_student_id_bot_student"),
            "bot_student",
            ["student_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot_student_extra", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_bot_student_extra_student_id_bot_student"),
            type_="foreignkey",
        )
        batch_op.drop_column("student_id")

    with op.batch_alter_table("bot_student", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("extra_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.create_foreign_key(
            "fk_bot_student_extra_id_bot_student_extra",
            "bot_student_extra",
            ["extra_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_unique_constraint("bot_student_extra_id_key", ["extra_id"])

    # ### end Alembic commands ###
