"""empty message

迁移 ID: 5e8186ded330
父迁移: d601e610448d
创建时间: 2025-02-15 23:45:26.299426

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

revision: str = "5e8186ded330"
down_revision: str | Sequence[str] | None = "d601e610448d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models_curriculum", schema=None) as batch_op:
        batch_op.drop_constraint("models_curriculum_config_id_key", type_="unique")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models_curriculum", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "models_curriculum_config_id_key", ["config_id"]
        )

    # ### end Alembic commands ###
