"""empty message

迁移 ID: 60d8eb7982ae
父迁移: 10ae65bbe3dd
创建时间: 2025-02-20 19:51:09.124379

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "60d8eb7982ae"
down_revision: str | Sequence[str] | None = "10ae65bbe3dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_files", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint("task_files_file_md5_key", type_="unique")
        batch_op.create_unique_constraint(None, ["file_id"])
        batch_op.create_foreign_key(
            batch_op.f("fk_task_files_file_id_models_files"),
            "models_files",
            ["file_id"],
            ["id"],
        )
        batch_op.drop_column("file_path")
        batch_op.drop_column("file_md5")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_files", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "file_md5", sa.VARCHAR(length=32), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "file_path", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_constraint(
            batch_op.f("fk_task_files_file_id_models_files"), type_="foreignkey"
        )
        batch_op.drop_constraint(None, type_="unique")
        batch_op.create_unique_constraint("task_files_file_md5_key", ["file_md5"])
        batch_op.drop_column("file_id")

    # ### end Alembic commands ###
