"""empty message

迁移 ID: 6d92c34a49fd
父迁移: 5e8186ded330
创建时间: 2025-02-16 13:58:49.070791

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6d92c34a49fd"
down_revision: str | Sequence[str] | None = "5e8186ded330"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models_sharecurriculumconfig",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "create_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "update_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["models_curriculumconfig.id"],
            name=op.f(
                "fk_models_sharecurriculumconfig_config_id_models_curriculumconfig"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_models_sharecurriculumconfig_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models_sharecurriculumconfig")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("models_curriculum", schema=None) as batch_op:
        # 修改列名
        batch_op.alter_column(
            "day",
            new_column_name="weekday",
            existing_type=sa.VARCHAR(length=255),
            nullable=False,
        )
        # batch_op.add_column(sa.Column("weekday", sa.String(length=255), nullable=False))
        # batch_op.drop_column("day")

    with op.batch_alter_table("models_curriculumconfig", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["user_id"])
        batch_op.drop_column("is_share")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models_curriculumconfig", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_share",
                sa.INTEGER(),
                server_default=sa.text("0"),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("models_curriculum", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "day", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_column("weekday")

    op.drop_table("models_sharecurriculumconfig")
    # ### end Alembic commands ###
