"""empty message

迁移 ID: 7a4e4b71bc1a
父迁移: 
创建时间: 2025-02-15 14:37:56.132973

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7a4e4b71bc1a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nickname", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=11), nullable=True),
        sa.Column("role", sa.String(length=32), server_default="user", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bind",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform_id", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_bind_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bind")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("bind", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bind_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_bind_platform_id"), ["platform_id"], unique=False
        )

    op.create_table(
        "group",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["user.id"], name=op.f("fk_group_creator_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "models_schedulednotice",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("notice_time", sa.DateTime(), nullable=True),
        sa.Column("recipients", sa.Text(), nullable=True),
        sa.Column("messages", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
            name=op.f("fk_models_schedulednotice_creator_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models_schedulednotice")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "teacher",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_teacher_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher")),
        sa.UniqueConstraint("user_id"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "classes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column(
            "join_method", sa.String(length=32), server_default="direct", nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
            name=op.f("fk_classes_group_id_group"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classes")),
        sa.UniqueConstraint("group_id"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "group_bind",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("platform_id", sa.String(length=32), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=False),
        sa.Column("guild_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
            name=op.f("fk_group_bind_group_id_group"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_bind")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("group_bind", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_group_bind_channel_id"), ["channel_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_group_bind_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_group_bind_platform_id"), ["platform_id"], unique=False
        )

    op.create_table(
        "models_classesjoinrequest",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("join_method", sa.String(length=32), nullable=False),
        sa.Column("describe", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["classes.id"],
            name=op.f("fk_models_classesjoinrequest_classes_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_models_classesjoinrequest_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models_classesjoinrequest")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "models_curriculumconfig",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("current_week", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_notify", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_share", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "create_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "update_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["classes.id"],
            name=op.f("fk_models_curriculumconfig_classes_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_models_curriculumconfig_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models_curriculumconfig")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "student",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.String(length=32), server_default="student", nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["classes.id"],
            name=op.f("fk_student_classes_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_student_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "creator_role",
            sa.String(length=32),
            server_default="teacher",
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["classes.id"],
            name=op.f("fk_tasks_classes_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
            name=op.f("fk_tasks_creator_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "teacher_classes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.String(length=32), server_default="teacher", nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["classes.id"],
            name=op.f("fk_teacher_classes_classes_id_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teacher.id"],
            name=op.f("fk_teacher_classes_teacher_id_teacher"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teacher_classes")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "models_curriculum",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("week", sa.String(), nullable=False),
        sa.Column("day", sa.String(), nullable=False),
        sa.Column("lesson", sa.String(length=255), nullable=False),
        sa.Column("course", sa.String(length=255), nullable=False),
        sa.Column("teacher", sa.String(length=255), nullable=False),
        sa.Column("classroom", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["models_curriculumconfig.id"],
            name=op.f("fk_models_curriculum_config_id_models_curriculumconfig"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models_curriculum")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "student_extra",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("sex", sa.String(length=32), nullable=True),
        sa.Column("student_code", sa.String(length=32), nullable=True),
        sa.Column("dormitory", sa.String(length=32), nullable=True),
        sa.Column("political_status", sa.String(length=32), nullable=True),
        sa.Column("family_contact", sa.String(length=11), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name=op.f("fk_student_extra_student_id_student"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_extra")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("student_extra", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_extra_student_code"), ["student_code"], unique=False
        )

    op.create_table(
        "task_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("file_md5", sa.String(length=32), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name=op.f("fk_task_files_student_id_student"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_task_files_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_files")),
        sa.UniqueConstraint("file_md5"),
        info={"bind_key": "models"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_files")
    with op.batch_alter_table("student_extra", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_student_extra_student_code"))

    op.drop_table("student_extra")
    op.drop_table("models_curriculum")
    op.drop_table("teacher_classes")
    op.drop_table("tasks")
    op.drop_table("student")
    op.drop_table("models_curriculumconfig")
    op.drop_table("models_classesjoinrequest")
    with op.batch_alter_table("group_bind", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_group_bind_platform_id"))
        batch_op.drop_index(batch_op.f("ix_group_bind_guild_id"))
        batch_op.drop_index(batch_op.f("ix_group_bind_channel_id"))

    op.drop_table("group_bind")
    op.drop_table("classes")
    op.drop_table("teacher")
    op.drop_table("models_schedulednotice")
    op.drop_table("group")
    with op.batch_alter_table("bind", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bind_platform_id"))
        batch_op.drop_index(batch_op.f("ix_bind_account_id"))

    op.drop_table("bind")
    op.drop_table("user")
    # ### end Alembic commands ###
