"""empty message

迁移 ID: 83bc179b65ef
父迁移: 488b5ff5a73e
创建时间: 2025-02-13 11:45:15.200991

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "83bc179b65ef"
down_revision: str | Sequence[str] | None = "488b5ff5a73e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "models_schedulednotice",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("notice_time", sa.DateTime(), nullable=True),
        sa.Column("recipients", sa.Text(), nullable=True),
        sa.Column("messages", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
            name=op.f("fk_models_schedulednotice_creator_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models_schedulednotice")),
        info={"bind_key": "models"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("models_schedulednotice")
    # ### end Alembic commands ###
