"""empty message

迁移 ID: 8419a3b15155
父迁移: daaaf1e3068c
创建时间: 2025-05-10 22:21:47.416133

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8419a3b15155"
down_revision: str | Sequence[str] | None = "daaaf1e3068c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot_group", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_bot_group_college_id_bot_college", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_bot_group_school_id_bot_school", type_="foreignkey"
        )
        batch_op.drop_column("college_id")
        batch_op.drop_column("school_id")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot_group", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("school_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("college_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_bot_group_school_id_bot_school", "bot_school", ["school_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_bot_group_college_id_bot_college", "bot_college", ["college_id"], ["id"]
        )

    # ### end Alembic commands ###
