"""empty message

迁移 ID: a172aeed2c22
父迁移: c8cdaf42b2cf
创建时间: 2025-02-18 17:19:58.337930

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a172aeed2c22"
down_revision: str | Sequence[str] | None = "c8cdaf42b2cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models_leave", schema=None) as batch_op:
        batch_op.add_column(sa.Column("classes_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("student_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint("fk_models_leave_user_id_user", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_models_leave_classes_id_classes"),
            "classes",
            ["classes_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_models_leave_student_id_student"),
            "student",
            ["student_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models_leave", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_models_leave_student_id_student"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_models_leave_classes_id_classes"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_models_leave_user_id_user",
            "user",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("student_id")
        batch_op.drop_column("classes_id")

    # ### end Alembic commands ###
