"""empty message

迁移 ID: c7438cea7672
父迁移: 2072b25f0341
创建时间: 2025-01-17 18:20:59.727755

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c7438cea7672"
down_revision: str | Sequence[str] | None = "2072b25f0341"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_extra",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("sex", sa.String(length=32), nullable=True),
        sa.Column("student_code", sa.String(length=32), nullable=True),
        sa.Column("dormitory", sa.String(length=32), nullable=True),
        sa.Column("political_status", sa.String(length=32), nullable=True),
        sa.Column("family_contact", sa.String(length=11), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
            name=op.f("fk_student_extra_student_id_student"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_extra")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("student_extra", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_extra_student_code"), ["student_code"], unique=False
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "role", sa.String(length=32), server_default="user", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("role")

    with op.batch_alter_table("student_extra", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_student_extra_student_code"))

    op.drop_table("student_extra")
    # ### end Alembic commands ###
