"""empty message

迁移 ID: daaaf1e3068c
父迁移: ec39cb48b105
创建时间: 2025-05-09 11:16:35.029399

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "daaaf1e3068c"
down_revision: str | Sequence[str] | None = "ec39cb48b105"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot_classes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("major", sa.String(length=64), nullable=True))

    with op.batch_alter_table("bot_student_extra", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("family_address", sa.String(length=255), nullable=True)
        )
        batch_op.add_column(sa.Column("nation", sa.String(length=32), nullable=True))
        batch_op.drop_column("sex")

    with op.batch_alter_table("bot_user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("gender", sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column("birthday", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot_user", schema=None) as batch_op:
        batch_op.drop_column("birthday")
        batch_op.drop_column("gender")

    with op.batch_alter_table("bot_student_extra", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("sex", sa.VARCHAR(length=32), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("nation")
        batch_op.drop_column("family_address")

    with op.batch_alter_table("bot_classes", schema=None) as batch_op:
        batch_op.drop_column("major")

    # ### end Alembic commands ###
