"""empty message

迁移 ID: e634135c3647
父迁移: 895cd0589dc7
创建时间: 2025-04-23 16:07:09.979123

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e634135c3647"
down_revision: str | Sequence[str] | None = "895cd0589dc7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_student_leave_approval",
        sa.Column("leave_id", sa.Integer(), nullable=False),
        sa.Column("approver_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["bot_user.id"],
            name=op.f("fk_bot_student_leave_approval_approver_id_bot_user"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["leave_id"],
            ["bot_student_leave.id"],
            name=op.f("fk_bot_student_leave_approval_leave_id_bot_student_leave"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_student_leave_approval")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("bot_student_leave", schema=None) as batch_op:
        batch_op.add_column(sa.Column("start_date", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("end_date", sa.DateTime(), nullable=True))
        batch_op.alter_column(
            "reason",
            existing_type=sa.VARCHAR(length=255),
            type_=sa.Text(),
            existing_nullable=False,
        )
        batch_op.drop_column("end_time")
        batch_op.drop_column("start_time")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot_student_leave", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "start_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "end_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
            )
        )
        batch_op.alter_column(
            "reason",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=255),
            existing_nullable=False,
        )
        batch_op.drop_column("end_date")
        batch_op.drop_column("start_date")

    op.drop_table("bot_student_leave_approval")
    # ### end Alembic commands ###
