"""empty message

迁移 ID: ec39cb48b105
父迁移: 21858dcc2085
创建时间: 2025-05-08 00:17:32.161814

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ec39cb48b105"
down_revision: str | Sequence[str] | None = "21858dcc2085"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_leave_workflow",
        sa.Column("less_day", sa.Integer(), server_default="0", nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column("shool_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["bot_classes.id"],
            name=op.f("fk_bot_leave_workflow_classes_id_bot_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shool_id"],
            ["bot_school.id"],
            name=op.f("fk_bot_leave_workflow_shool_id_bot_school"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_leave_workflow")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("bot_student_leave_approval", schema=None) as batch_op:
        batch_op.add_column(sa.Column("workflow_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_bot_student_leave_approval_workflow_id_bot_leave_workflow"),
            "bot_leave_workflow",
            ["workflow_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("bot_student_leave_approval", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_bot_student_leave_approval_workflow_id_bot_leave_workflow"),
            type_="foreignkey",
        )
        batch_op.drop_column("workflow_id")

    op.drop_table("bot_leave_workflow")
    # ### end Alembic commands ###
