"""empty message

迁移 ID: ed13facfbb38
父迁移: 
创建时间: 2025-04-03 19:00:11.511295

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ed13facfbb38"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_files",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("file_md5", sa.String(length=32), nullable=False),
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("suffix", sa.String(length=12), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_files")),
        sa.UniqueConstraint("file_md5"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_group_settings",
        sa.Column(
            "join_method", sa.String(length=32), server_default="direct", nullable=True
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_group_settings")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_school",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_school")),
        sa.UniqueConstraint("name"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_student_extra",
        sa.Column("sex", sa.String(length=32), nullable=True),
        sa.Column("student_code", sa.String(length=32), nullable=True),
        sa.Column("dormitory", sa.String(length=32), nullable=True),
        sa.Column("political_status", sa.String(length=32), nullable=True),
        sa.Column("family_contact", sa.String(length=11), nullable=True),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_student_extra")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("bot_student_extra", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bot_student_extra_student_code"),
            ["student_code"],
            unique=False,
        )

    op.create_table(
        "bot_user",
        sa.Column("nickname", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("avatar", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=11), nullable=True),
        sa.Column("role", sa.String(length=32), server_default="user", nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_user")),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
        sa.UniqueConstraint("username"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_college",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["bot_school.id"],
            name=op.f("fk_bot_college_school_id_bot_school"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_college")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_curricula_schedule",
        sa.Column("shool_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["shool_id"],
            ["bot_school.id"],
            name=op.f("fk_bot_curricula_schedule_shool_id_bot_school"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_curricula_schedule")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_education_system",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("account", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["bot_school.id"],
            name=op.f("fk_bot_education_system_school_id_bot_school"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["bot_user.id"],
            name=op.f("fk_bot_education_system_user_id_bot_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_education_system")),
        sa.UniqueConstraint("account"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_scheduled_notice",
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("notice_time", sa.DateTime(), nullable=True),
        sa.Column("recipients", sa.Text(), nullable=True),
        sa.Column("messages", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["bot_user.id"],
            name=op.f("fk_bot_scheduled_notice_creator_id_bot_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_scheduled_notice")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_user_bind",
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("platform_id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["bot_user.id"],
            name=op.f("fk_bot_user_bind_user_id_bot_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_user_bind")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("bot_user_bind", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bot_user_bind_account_id"), ["account_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_bot_user_bind_platform_id"), ["platform_id"], unique=False
        )

    op.create_table(
        "bot_group",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("settings_id", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=True),
        sa.Column("college_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["college_id"],
            ["bot_college.id"],
            name=op.f("fk_bot_group_college_id_bot_college"),
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["bot_user.id"],
            name=op.f("fk_bot_group_creator_id_bot_user"),
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["bot_school.id"],
            name=op.f("fk_bot_group_school_id_bot_school"),
        ),
        sa.ForeignKeyConstraint(
            ["settings_id"],
            ["bot_group_settings.id"],
            name=op.f("fk_bot_group_settings_id_bot_group_settings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_group")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_teacher",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "role", sa.String(length=64), server_default="teacher", nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=True),
        sa.Column("college_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["college_id"],
            ["bot_college.id"],
            name=op.f("fk_bot_teacher_college_id_bot_college"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["bot_school.id"],
            name=op.f("fk_bot_teacher_school_id_bot_school"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["bot_user.id"],
            name=op.f("fk_bot_teacher_user_id_bot_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_teacher")),
        sa.UniqueConstraint("user_id"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_classes",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("college_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["college_id"],
            ["bot_college.id"],
            name=op.f("fk_bot_classes_college_id_bot_college"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["bot_group.id"],
            name=op.f("fk_bot_classes_group_id_bot_group"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_classes")),
        sa.UniqueConstraint("group_id"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_group_bind",
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("platform_id", sa.String(length=64), nullable=False),
        sa.Column("channel_id", sa.String(length=64), nullable=False),
        sa.Column("guild_id", sa.String(length=64), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["bot_group.id"],
            name=op.f("fk_bot_group_bind_group_id_bot_group"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_group_bind")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("bot_group_bind", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bot_group_bind_channel_id"), ["channel_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_bot_group_bind_guild_id"), ["guild_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_bot_group_bind_platform_id"), ["platform_id"], unique=False
        )

    op.create_table(
        "bot_classes_join_request",
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("join_method", sa.String(length=32), nullable=False),
        sa.Column("describe", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["bot_classes.id"],
            name=op.f("fk_bot_classes_join_request_classes_id_bot_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["bot_user.id"],
            name=op.f("fk_bot_classes_join_request_user_id_bot_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_classes_join_request")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_classes_leave_config",
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column(
            "notify_role", sa.String(length=255), server_default="[]", nullable=False
        ),
        sa.Column(
            "create_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "update_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["bot_classes.id"],
            name=op.f("fk_bot_classes_leave_config_classes_id_bot_classes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_classes_leave_config")),
        sa.UniqueConstraint("classes_id"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_curricula_config",
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("classes_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("current_week", sa.Integer(), server_default="1", nullable=False),
        sa.Column("is_notify", sa.Integer(), server_default="0", nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=True),
        sa.Column(
            "create_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "update_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["bot_classes.id"],
            name=op.f("fk_bot_curricula_config_classes_id_bot_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["bot_school.id"],
            name=op.f("fk_bot_curricula_config_school_id_bot_school"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["bot_user.id"],
            name=op.f("fk_bot_curricula_config_user_id_bot_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_curricula_config")),
        sa.UniqueConstraint("classes_id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("user_id"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_student",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column("school_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.String(length=32), server_default="student", nullable=False
        ),
        sa.Column("extra_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["bot_classes.id"],
            name=op.f("fk_bot_student_classes_id_bot_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["extra_id"],
            ["bot_student_extra.id"],
            name=op.f("fk_bot_student_extra_id_bot_student_extra"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["bot_school.id"],
            name=op.f("fk_bot_student_school_id_bot_school"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["bot_user.id"],
            name=op.f("fk_bot_student_user_id_bot_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_student")),
        sa.UniqueConstraint("extra_id"),
        sa.UniqueConstraint("user_id"),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_tasks",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["bot_classes.id"],
            name=op.f("fk_bot_tasks_classes_id_bot_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["bot_user.id"],
            name=op.f("fk_bot_tasks_creator_id_bot_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_tasks")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_teacher_classes",
        sa.Column("teacher_id", sa.Integer(), nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.String(length=32), server_default="teacher", nullable=False
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["bot_classes.id"],
            name=op.f("fk_bot_teacher_classes_classes_id_bot_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["bot_teacher.id"],
            name=op.f("fk_bot_teacher_classes_teacher_id_bot_teacher"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_teacher_classes")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_curricula",
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("week", sa.String(length=255), nullable=False),
        sa.Column("weekday", sa.String(length=255), nullable=False),
        sa.Column("lesson", sa.String(length=255), nullable=False),
        sa.Column("course", sa.String(length=255), nullable=False),
        sa.Column("teacher", sa.String(length=64), nullable=True),
        sa.Column("classroom", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["bot_curricula_config.id"],
            name=op.f("fk_bot_curricula_config_id_bot_curricula_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_curricula")),
        info={"bind_key": "models"},
    )
    with op.batch_alter_table("bot_curricula", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_bot_curricula_course"), ["course"], unique=False
        )

    op.create_table(
        "bot_share_curricula_config",
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "create_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "update_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["bot_curricula_config.id"],
            name=op.f("fk_bot_share_curricula_config_config_id_bot_curricula_config"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["bot_user.id"],
            name=op.f("fk_bot_share_curricula_config_user_id_bot_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_share_curricula_config")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_student_leave",
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("classes_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["classes_id"],
            ["bot_classes.id"],
            name=op.f("fk_bot_student_leave_classes_id_bot_classes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["bot_files.id"],
            name=op.f("fk_bot_student_leave_file_id_bot_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["bot_student.id"],
            name=op.f("fk_bot_student_leave_student_id_bot_student"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_student_leave")),
        info={"bind_key": "models"},
    )
    op.create_table(
        "bot_task_commits",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["bot_files.id"],
            name=op.f("fk_bot_task_commits_file_id_bot_files"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["bot_student.id"],
            name=op.f("fk_bot_task_commits_student_id_bot_student"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["bot_tasks.id"],
            name=op.f("fk_bot_task_commits_task_id_bot_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_task_commits")),
        sa.UniqueConstraint("file_id"),
        info={"bind_key": "models"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bot_task_commits")
    op.drop_table("bot_student_leave")
    op.drop_table("bot_share_curricula_config")
    with op.batch_alter_table("bot_curricula", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_curricula_course"))

    op.drop_table("bot_curricula")
    op.drop_table("bot_teacher_classes")
    op.drop_table("bot_tasks")
    op.drop_table("bot_student")
    op.drop_table("bot_curricula_config")
    op.drop_table("bot_classes_leave_config")
    op.drop_table("bot_classes_join_request")
    with op.batch_alter_table("bot_group_bind", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_group_bind_platform_id"))
        batch_op.drop_index(batch_op.f("ix_bot_group_bind_guild_id"))
        batch_op.drop_index(batch_op.f("ix_bot_group_bind_channel_id"))

    op.drop_table("bot_group_bind")
    op.drop_table("bot_classes")
    op.drop_table("bot_teacher")
    op.drop_table("bot_group")
    with op.batch_alter_table("bot_user_bind", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_user_bind_platform_id"))
        batch_op.drop_index(batch_op.f("ix_bot_user_bind_account_id"))

    op.drop_table("bot_user_bind")
    op.drop_table("bot_scheduled_notice")
    op.drop_table("bot_education_system")
    op.drop_table("bot_curricula_schedule")
    op.drop_table("bot_college")
    op.drop_table("bot_user")
    with op.batch_alter_table("bot_student_extra", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_student_extra_student_code"))

    op.drop_table("bot_student_extra")
    op.drop_table("bot_school")
    op.drop_table("bot_group_settings")
    op.drop_table("bot_files")
    # ### end Alembic commands ###
